# Generated by Django 4.2.16 on 2024-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_reservation_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.CharField(choices=[('11:00 - 13:00', '11:00 - 13:00'), ('13:00 - 15:00', '13:00 - 15:00'), ('15:00 - 17:00', '15:00 - 17:00'), ('17:00 - 19:00', '17:00 - 19:00'), ('19:00 - 21:00', '19:00 - 21:00'), ('21:00 - 23:00', '21:00 - 23:00')], max_length=20),
        ),
    ]
